// Build script — generates env.js from environment variables
// Used by Vercel during deployment
const fs = require('fs');

const env = {
  FIREBASE_API_KEY: process.env.FIREBASE_API_KEY || '',
  FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN || '',
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID || '',
  FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET || '',
  FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID || '',
  FIREBASE_APP_ID: process.env.FIREBASE_APP_ID || '',
  FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID || '',
  SUPABASE_URL: process.env.SUPABASE_URL || '',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || '',
  GROQ_API_KEY: process.env.GROQ_API_KEY || ''
};

const content = `// Auto-generated by build script — DO NOT EDIT\nexport const ENV = ${JSON.stringify(env, null, 2)};\n`;

fs.writeFileSync('env.js', content);
console.log('✅ env.js generated from environment variables');
